### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by roberthenry1977** [Tommrodrigues/homebridge-http-thermometer#1]
Hi,
I am new to Homebridge so am possibly doing something wrong. When I attempt to install the plugin I get the following error (captured install line incase my mistake is there) - see below.
I am using a raspberry pi 3 B with standard Raspbian OS. I have successfully run another plugin on Homebridge (http relay) and had my esp32 connect through to Homekit and operate as expected. The only other things I have tweaked on the raspberry pi is to enable mDNS and change the name as below (I only have the pi for the bridge and all the gadgets I have made).

pi@HenryHomeBridge:~ $ npm install -g homebridge-http-thermometer
/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:57
log.progressEnabled = log.gauge.isEnabled()
                                ^

TypeError: log.gauge.isEnabled is not a function
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npmlog/log.js:57:33)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at /usr/local/lib/node_modules/npm/bin/npm-cli.js:22:13
    at Object.<anonymous> (/usr/local/lib/node_modules/npm/bin/npm-cli.js:152:3)

**Comment by roberthenry1977** [comment]
I just googled that error and it looks like it some general npm error - so this is clearly on my end.
I am working my way through all the ways people have resolved it and post if I find a solution

**Comment by roberthenry1977** [comment]
Drastic measures taken and it worked: I completely removed node, and then manually reinstalled everything. then installed your plugin. I have updated the config.json and launched Homebridge and it seems to be working fine.
Now to make the hardware side!

**Comment by phenotypic** [comment]
Glad you were able to solve your issue. Enjoy!
